name = "regionofvaspiria"
compatibility_date = "2026-07-01"
main = "./src/worker.ts"
routes = [
	{ pattern = "regionofvaspiria.com", custom_domain = true }
]

[vars]
ROBLOX_CLIENT_ID = "8125208813163703919"
ROBLOX_OAUTH_REDIRECT_URI = "https://regionofvaspiria.com/link-roblox"

[[kv_namespaces]]
binding = "SYNC_PROGRESS"
id = "63cbd7bd5f4949a69c900b8012aa5114"
preview_id = "REPLACE_WITH_SYNC_PROGRESS_KV_PREVIEW_ID"

[[kv_namespaces]]
binding = "ROBLOX_OAUTH_CODES"
id = "b3f77cb42e9f40b099263673dd823e71"
preview_id = "REPLACE_WITH_ROBLOX_OAUTH_CODES_KV_PREVIEW_ID"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
